// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeViewer: typeof import('./components/CodeViewer.vue')['default']
    DynamicPropertiesPanel: typeof import('./components/DynamicPropertiesPanel.vue')['default']
    Palette: typeof import('./components/palette/Palette.vue')['default']
    PropertiesEditor: typeof import('./components/PropertiesEditor.vue')['default']
    TestPropertiesEditor: typeof import('./components/test/TestPropertiesEditor.vue')['default']
  }
}

export {}
